name: Build .NET Framework Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.x # Use the version of .NET Framework you need

    - name: Build application
      run: |
        nuget restore WinboxStatsChecker.sln # Restore NuGet packages
        msbuild /p:Configuration=Release WinboxStatsChecker.sln # Build the solution


