name: .NET Framework Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' # Set the environment variable

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore WinboxStatsChecker.sln

    - name: Build Solution
      run: |
        msbuild.exe WinboxStatsChecker.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        